name: monitoring_alerts_app
description: A monitoring and alerts application with Flutter.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^0.13.6
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.1
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true